### ISSUE TITLE
add cpp_build base image

### ISSUE THREAD

**Issue by Sild** [Sild/docker_builds#1]
Need to build new docker image to build & run cpp apps (such as [telegram_bot](https://github.com/Sild/telegram_bot) )
It have to base on alpine linux to reduce unnecessary disk space usage

Required libraries & packages ( for beginning ):
- cmake
- g++
- boost1.59+ (1.62 is preferred)
- openssl
- git

Build duration doesn't matter.

Success criteria:
The following workflow will start the application

```
git clone https://github.com/Sild/telegram_bot
mkdir telegram_bot/build && cd telegram_bot/build
cmake ../
cmake --build .
./assistant 
```

Docker Image build code ( Dockerfile with dependencies ) should be placed in cpp_build folder.

**Comment by thedilletante** [comment]
Opened PR https://github.com/Sild/telegram_bot/pull/2
Success criteria is not comprehensive. Need to `git submodule update --init --recursive` after `clone`

**Comment by thedilletante** [comment]
fixed
